# Project information
site_name: "KeybrL's Blog"
site_url: 'https://blog.keybrl.com/'
repo_url: 'https://github.com/keybrl/my_Blog-2018plus/'
repo_name: 'keybrl/my_Blog-2018plus'
edit_uri: ''
site_description: 'This site is the Blog of KeybrL.'
site_author: 'KeybrL'
copyright: 'Copyright &copy; <a href="https://blog.keybrl.com/">KeybrL</a> All Rights Reserved.'
google_analytics: ['UA-119555935-1', 'blog.keybrl.com']
remote_branch: gh-pages
remote_name: origin

# Documentation layout
nav:
    - 主页: 'index.md'
    - 无聊的日常:
        - '无聊的日常 - 导读': 'boring/introduction.md'
        - '软路由与NAS(3) - 外壳': 'boring/2019-02-22-router3_shell.md'
        - '软路由与NAS(2) - 软件平台搭建': 'boring/2019-02-18-router2_software.md'
        - '2018年终总结': 'boring/2018-12-31-summary.md'
        - '软路由与NAS(1) - 硬件平台搭建': 'boring/2018-11-02-router1_hardware.md'
#        - 'New Surface Pro 初体验（未完成）': 'boring/2018-09-07-new_surface_pro.md'
        - '虹吸壶冲泡咖啡': 'boring/2018-03-03-siphon.md'
        - 'IKBC Poker2 加灯历程': 'boring/2018-01-20-lighted-poker2.md'
    - 专业相关:
        - '专业相关的文章 - 导读': 'professional/introduction.md'
        - 'Windows 常用注册表项': 'professional/2018-10-23-Windows-regedit.md'
        - 'Nginx常用配置套路（未完成）': 'professional/2018-07-02-nginx-configure.md'
#        - 'Python-Markdown支持的Markdown扩展（未完成）': 'professional/2018-05-24-python-markdown.md'
        - '通过MkDocs搭建个人博客': 'professional/2018-05-19-mkdocs-blog.md'
        - 'HTTP/1.1 - 状态码定义（翻译）（未完成）': 'professional/2017-12-19-HTTP11-Status-Code-Definitions-zh.md'
        - 'CentOS中通过Nginx和uWSGI部署Flask项目': 'professional/2017-08-01-Nginx_uWSGI_Flask_in_CentOS.md'
        - '使用Python的smtplib和email发送邮件': 'professional/2017-04-09-Use-smtplib-and-email-in-python-to-send-email.md'
        - 'C语言上机心得': 'professional/2016-12-30-C-study.md'
        - 'Markdown语法基础': 'professional/2016-11-13-The-base-of-grammar-in-Markdown.md'
        - '从冯·诺依曼体系结构起航': 'professional/2016-10-22-John-Von-Nouma.md'
    - 转载:
        - '转载文章 - 导读': 'repost/introduction.md'
        - 'HTTP/1.1 - Status Code Definitions': 'repost/2017-12-19-HTTP11-Status-Code-Definitions-en.md'
    - SS::STA回顾:
        - 'SS:STA活动回顾 - 导读': 'sssta/introduction.md'
        - 'Web 2017下半年活动内容清单': 'sssta/2018-01-19-SSSTA-Web-list2017.md'
        - 'Web4.0 - 前端页面的布局': 'sssta/2017-12-03-SSSTA-Web4.0.md'
        - 'Web3 - Python复习': 'sssta/2017-12-03-SSSTA-Web3.md'
        - 'Web2.0 - HTML与CSS入门': 'sssta/2017-11-19-SSSTA-Web2.0.md'
        - 'Web1 - Web应用概论': 'sssta/2017-11-12-SSSTA-Web1.md'
        - 'Python入门2': 'sssta/2017-10-08-SSSTA-Python2.md'
        - '在GitHub上通过Jekyll搭建个人博客': 'sssta/2017-10-08-SSSTA-Blog.md'
        - 'Python入门1': 'sssta/2017-09-29-SSSTA-Python1.md'
    - 垃圾代码:
        - '垃圾代码 - 导读': 'projects/introduction.md'
        - 'keybrl-mines - 优雅的扫雷从此无处不在': 'projects/2018-10-14-Project-keybrl-mines.md'
        - '概率神教 - 优秀的问题解决方案': 'projects/2017-11-19-Project-Coin.md'
        - 'Tetris': 'projects/2017-06-12-Project-Tetris.md'
        - '生命游戏': 'projects/2017-04-30-Project-Game_or_Life.md'
    - 留言板: 'board.md'
    - 友情链接: 'links.md'
    - 小额赞助: 'donate.md'

# Build directories
theme:
    name: 'material'
    language: 'zh'
    logo:
        icon: 'code'
    palette:
        primary: 'blue grey'
        accent: 'light blue'
    custom_dir: 'theme'
#docs_dir: 'docs'
#site_dir: 'site'
#extra_css: []
extra_javascript:
  - '//blog-assets.keybrl.com/plugins/MathJax/unpacked/MathJax.js?config=TeX-MML-AM_CHTML'  # //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
#extra_templates: []
extra:
    search:
        language: 'en, jp'
    repo_icon: 'github'
    social:
    - type: 'github'
      link: 'https://github.com/keybrl'
    - type: 'steam'
      link: 'https://steamcommunity.com/id/keybrl'
    - type: 'envelope'
      link: 'mailto:keyboard-l@outlook.com'
    - type: 'rss'
      link: 'https://blog.keybrl.com/feed.xml'

# Preview controls
use_directory_urls: false
#strict: false
dev_addr: 0.0.0.0:80

# Formatting options
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - markdown_newtab
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#plugins: ['search']
